### ISSUE TITLE
Make sure line numbers are counted correctly in multi line strings

### ISSUE THREAD

**Issue by droggan** [Helliaca/Custom-UnCool-Compiler#3]
It seems line numbers are not counted correctly if a string contains a line break. Test with something like:

"foo
bar
baz"

hello_world

**Comment by Helliaca** [comment]
Note: As of now, line number will equate to where the string ends. (Where LexScanner stops reading the token)

**Comment by Helliaca** [comment]
Nvm, its fixed now.
